import { chromium } from "playwright";
const URL="http://127.0.0.1:5174"; const browser=await chromium.launch();
const page=await browser.newPage({viewport:{width:1600,height:1000}});
const errs=[]; page.on("console",m=>{if(m.type()==="error")errs.push(m.text().slice(0,140));});
await page.goto(URL,{waitUntil:"networkidle"}); await page.waitForTimeout(1200);
await page.getByRole("button",{name:/Sign in|دخول/}).first().click();
const dlg=page.locator("[role='dialog']"); await dlg.waitFor({state:"visible"});
await dlg.locator("input").nth(0).fill("zainab@koub.iq"); await dlg.locator("input").nth(1).fill("test");
await dlg.locator("button[type='submit']").click(); await page.waitForTimeout(5000);
await page.getByRole("button",{name:/^POS$/}).first().click().catch(()=>{}); await page.waitForTimeout(3000);
await page.locator("div").filter({hasText:/^Zainab Hassancashier$/}).first().click().catch(()=>{}); await page.waitForTimeout(1200);
await page.getByRole("button",{name:/Start shift|ابدأ الوردية/}).first().click().catch(()=>{}); await page.waitForTimeout(6000);
await page.screenshot({path:"verification/koub-grid-all.png",fullPage:false});
// add OJ under All (direct add) then charge to confirm sale still works
await page.locator("button.card, .card").filter({hasText:/Orange Juice/}).first().click().catch(e=>errs.push("addclick:"+e));
await page.waitForTimeout(1500);
let saleResp="(none)"; page.on("response", async r=>{ if(r.url().includes("kiosk_sale")){ try{const j=await r.json(); saleResp=JSON.stringify(j.result||j.error).slice(0,160);}catch(e){} } });
await page.getByRole("button",{name:/Charge/}).first().click().catch(()=>{}); await page.waitForTimeout(2000);
await page.locator("[class*='card']").filter({hasText:/configured POS method/}).filter({hasText:/Cash/}).first().click().catch(()=>{});
await page.waitForTimeout(5000);
const body=await page.locator("body").innerText();
console.log("SALE:", saleResp);
console.log("RESULT:", body.includes("Payment complete")?"Payment complete ✓":body.includes("Sale failed")?"Sale failed ✗":"?");
console.log("ERRORS:", JSON.stringify(errs.slice(0,4)));
await browser.close();
