export type BayaanSectionId =
  | "overview"
  | "insights"
  | "kiosks"
  | "sales"
  | "warehouses"
  | "items"
  | "inventory"
  | "products"
  | "closing"
  | "waste"
  | "suppliers"
  | "staff"
  | "finance"
  | "reports";

export type RegistrySectionId = BayaanSectionId | "canvas" | "studio";

export type VisualKind =
  | "kpi-grid"
  | "rank-list"
  | "status-card"
  | "table"
  | "expanded-table"
  | "meter"
  | "progress-list"
  | "donut"
  | "bar-chart"
  | "area-chart"
  | "line-chart"
  | "heatmap"
  | "stacked-breakdown"
  | "timeline"
  | "ai-explanation"
  | "proposal-card";

// "human-confirm" is AI-renderable like "proposal-only", but unlike an inert
// proposal it carries a human-clickable Confirm that commits through a
// deterministic, role-gated, audited backend route. The AI only pre-fills the
// draft — it never writes. "human-action" remains AI-forbidden (a surface only a
// human opens and operates, never pre-filled by a plan).
export type InteractionMode = "read-only" | "proposal-only" | "human-confirm" | "human-action";

export type CanvasSize = "small" | "medium" | "wide" | "full";

export type DataPackId =
  | "overview"
  | "sales"
  | "kiosks"
  | "warehouses"
  | "items"
  | "inventory"
  | "products"
  | "closing"
  | "waste"
  | "suppliers"
  | "staff"
  | "finance"
  | "reports";

export type AiDashboardIntent =
  | "executive-summary"
  | "kiosk-diagnosis"
  | "waste-anomaly-review"
  | "stock-allocation"
  | "close-review"
  | "recipe-margin-review"
  | "payment-reconciliation"
  | "staff-coaching"
  | "warehouse-topology"
  | "catalog-lookup"
  | "catalog-create";

export type SourceRefRequirement =
  | "pos.order"
  | "pos.payment"
  | "pos.session"
  | "stock.quant"
  | "stock.picking"
  | "stock.location"
  | "purchase.order"
  | "product.template"
  | "bayaan.recipe"
  | "bayaan.consumption.ledger"
  | "bayaan.shift.close"
  | "bayaan.shift.close.line"
  | "bayaan.waste.entry"
  | "bayaan.kiosk"
  | "hr.employee"
  | "hr.attendance"
  | "account.move"
  | "report.pack";

export type DashboardComponentEntry = {
  readonly id: string;
  readonly label: string;
  readonly sectionId: RegistrySectionId;
  readonly sourcePath: string;
  readonly sourceLines: string;
  readonly visualKind: VisualKind;
  readonly bestFor: readonly AiDashboardIntent[];
  readonly dataPacks: readonly DataPackId[];
  readonly dataContract: string;
  readonly sourceRefsRequired: readonly SourceRefRequirement[];
  readonly interactionMode: InteractionMode;
  readonly canvasSizes: readonly CanvasSize[];
  readonly notes?: string;
};

export const componentRegistry = [
  {
    id: "canvas.headline",
    label: "Canvas headline diagnosis",
    sectionId: "canvas",
    sourcePath: "apps/kiosk-pos/src/exact-design/ExactKioskApp.jsx",
    sourceLines: "4871-4880",
    visualKind: "ai-explanation",
    bestFor: ["executive-summary", "kiosk-diagnosis", "recipe-margin-review", "close-review"],
    dataPacks: ["overview", "kiosks", "products", "closing"],
    dataContract: "Single claim with title, delta, body, confidence, sparkline, and source refs.",
    sourceRefsRequired: ["pos.order", "bayaan.consumption.ledger", "bayaan.shift.close"],
    interactionMode: "read-only",
    canvasSizes: ["medium", "wide"],
  },
  {
    id: "canvas.bars",
    label: "Canvas comparison bars",
    sectionId: "canvas",
    sourcePath: "apps/kiosk-pos/src/exact-design/ExactKioskApp.jsx",
    sourceLines: "4881-4895",
    visualKind: "bar-chart",
    bestFor: ["executive-summary", "recipe-margin-review", "payment-reconciliation"],
    dataPacks: ["overview", "sales", "products", "finance"],
    dataContract: "Current and previous comparable values by period or category.",
    sourceRefsRequired: ["pos.order", "report.pack"],
    interactionMode: "read-only",
    canvasSizes: ["small", "medium"],
  },
  {
    id: "canvas.forecast",
    label: "Canvas forecast range",
    sectionId: "canvas",
    sourcePath: "apps/kiosk-pos/src/exact-design/ExactKioskApp.jsx",
    sourceLines: "4897-4904",
    visualKind: "ai-explanation",
    bestFor: ["executive-summary", "recipe-margin-review"],
    dataPacks: ["overview", "reports", "sales"],
    dataContract: "Forecast value with low/high range, note, confidence, and source refs.",
    sourceRefsRequired: ["pos.order", "report.pack"],
    interactionMode: "read-only",
    canvasSizes: ["small", "medium"],
  },
  {
    id: "canvas.rank",
    label: "Canvas ranked comparison",
    sectionId: "canvas",
    sourcePath: "apps/kiosk-pos/src/exact-design/ExactKioskApp.jsx",
    sourceLines: "4906-4916",
    visualKind: "rank-list",
    bestFor: ["staff-coaching", "kiosk-diagnosis", "recipe-margin-review"],
    dataPacks: ["staff", "kiosks", "products"],
    dataContract: "Ranked rows with value, target, optional muted baseline, and source refs.",
    sourceRefsRequired: ["pos.order", "bayaan.shift.close", "hr.employee"],
    interactionMode: "read-only",
    canvasSizes: ["small", "medium"],
  },
  {
    id: "canvas.runway",
    label: "Canvas stock runway",
    sectionId: "canvas",
    sourcePath: "apps/kiosk-pos/src/exact-design/ExactKioskApp.jsx",
    sourceLines: "4918-4930",
    visualKind: "meter",
    bestFor: ["stock-allocation", "executive-summary"],
    dataPacks: ["inventory", "warehouses"],
    dataContract: "Rows with category, days of cover, target cover, ok flag, and source refs.",
    sourceRefsRequired: ["stock.quant", "stock.location"],
    interactionMode: "read-only",
    canvasSizes: ["medium", "wide"],
  },
  {
    id: "canvas.stack",
    label: "Canvas variance breakdown",
    sectionId: "canvas",
    sourcePath: "apps/kiosk-pos/src/exact-design/ExactKioskApp.jsx",
    sourceLines: "4950-4960",
    visualKind: "stacked-breakdown",
    bestFor: ["kiosk-diagnosis", "close-review", "waste-anomaly-review"],
    dataPacks: ["kiosks", "closing", "waste", "sales"],
    dataContract: "Segments with label, value, color, total, and source refs.",
    sourceRefsRequired: ["pos.order", "bayaan.shift.close", "bayaan.waste.entry"],
    interactionMode: "read-only",
    canvasSizes: ["medium", "wide"],
  },
  {
    id: "canvas.actions",
    label: "Canvas proposed next steps",
    sectionId: "canvas",
    sourcePath: "apps/kiosk-pos/src/exact-design/ExactKioskApp.jsx",
    sourceLines: "4962-4969",
    visualKind: "proposal-card",
    bestFor: ["stock-allocation", "kiosk-diagnosis", "waste-anomaly-review", "close-review"],
    dataPacks: ["inventory", "kiosks", "waste", "closing"],
    dataContract: "Recommended next steps with labels and rationale, without executable handlers.",
    sourceRefsRequired: ["stock.quant", "bayaan.shift.close", "bayaan.waste.entry"],
    interactionMode: "proposal-only",
    canvasSizes: ["small", "medium"],
    notes: "In v1 this component must render recommendations only, never approve or create records.",
  },
  {
    id: "catalog.product_draft",
    label: "AI product + recipe draft",
    sectionId: "canvas",
    sourcePath: "apps/kiosk-pos/src/exact-design/ExactKioskApp.jsx",
    sourceLines: "8780-8964",
    visualKind: "proposal-card",
    bestFor: ["catalog-create"],
    dataPacks: ["products", "items"],
    dataContract: "Editable product+recipe draft pre-filled by the AI from a create request; a human edits and confirms it, which calls the deterministic /product_create_bundle route.",
    sourceRefsRequired: ["product.template", "bayaan.recipe"],
    interactionMode: "human-confirm",
    canvasSizes: ["wide", "full"],
    notes: "AI pre-fills the draft only; it never writes. Confirm commits via /product_create_bundle, guarded by procurement+manager scope and audited.",
  },
  {
    id: "canvas.hourly",
    label: "Canvas hourly timeline",
    sectionId: "canvas",
    sourcePath: "apps/kiosk-pos/src/exact-design/ExactKioskApp.jsx",
    sourceLines: "4971-4976",
    visualKind: "timeline",
    bestFor: ["kiosk-diagnosis", "payment-reconciliation", "executive-summary"],
    dataPacks: ["sales", "kiosks"],
    dataContract: "Twenty-four hourly values with current hour and optional outage range.",
    sourceRefsRequired: ["pos.order", "stock.quant"],
    interactionMode: "read-only",
    canvasSizes: ["wide", "full"],
  },
  {
    id: "canvas.heatmap",
    label: "Canvas correlation heatmap",
    sectionId: "canvas",
    sourcePath: "apps/kiosk-pos/src/exact-design/ExactKioskApp.jsx",
    sourceLines: "4998-5005",
    visualKind: "heatmap",
    bestFor: ["waste-anomaly-review", "recipe-margin-review", "executive-summary"],
    dataPacks: ["waste", "sales", "products"],
    dataContract: "Matrix or paired points for correlation and anomaly density.",
    sourceRefsRequired: ["pos.order", "bayaan.waste.entry"],
    interactionMode: "read-only",
    canvasSizes: ["medium", "wide"],
  },
  {
    id: "canvas.rank-big",
    label: "Canvas recommendation ranking",
    sectionId: "canvas",
    sourcePath: "apps/kiosk-pos/src/exact-design/ExactKioskApp.jsx",
    sourceLines: "4987-4996",
    visualKind: "rank-list",
    bestFor: ["recipe-margin-review", "executive-summary"],
    dataPacks: ["products", "sales"],
    dataContract: "Ranked recommendation rows with score, attach rate, margin, reason, and source refs.",
    sourceRefsRequired: ["pos.order", "product.template", "bayaan.recipe"],
    interactionMode: "read-only",
    canvasSizes: ["wide", "full"],
  },
  {
    id: "canvas.wastegrid",
    label: "Canvas waste heatmap",
    sectionId: "canvas",
    sourcePath: "apps/kiosk-pos/src/exact-design/ExactKioskApp.jsx",
    sourceLines: "5025-5031",
    visualKind: "heatmap",
    bestFor: ["waste-anomaly-review", "close-review"],
    dataPacks: ["waste", "closing"],
    dataContract: "Kiosk by day waste matrix with anomaly highlighting and source refs.",
    sourceRefsRequired: ["bayaan.waste.entry", "bayaan.shift.close"],
    interactionMode: "read-only",
    canvasSizes: ["wide", "full"],
  },
  {
    id: "overview.kpi_panel",
    label: "Overview KPI panel",
    sectionId: "overview",
    sourcePath: "apps/bayaan-dashboard/src/components/bayaan/overview-dashboard.tsx",
    sourceLines: "98-147",
    visualKind: "kpi-grid",
    bestFor: ["executive-summary"],
    dataPacks: ["overview", "sales", "finance", "kiosks"],
    dataContract: "Fleet metrics for sales, profit, cash, digital payments, status, orders, waste, and variance.",
    sourceRefsRequired: ["pos.order", "pos.payment", "bayaan.shift.close", "report.pack"],
    interactionMode: "read-only",
    canvasSizes: ["medium", "wide"],
  },
  {
    id: "overview.top_performers_rank",
    label: "Top performers",
    sectionId: "overview",
    sourcePath: "apps/bayaan-dashboard/src/components/bayaan/overview-dashboard.tsx",
    sourceLines: "183-194",
    visualKind: "rank-list",
    bestFor: ["executive-summary", "kiosk-diagnosis"],
    dataPacks: ["overview", "kiosks", "sales"],
    dataContract: "Ranked kiosk revenue rows with percent bars and status variant.",
    sourceRefsRequired: ["pos.order", "bayaan.kiosk"],
    interactionMode: "read-only",
    canvasSizes: ["small", "medium"],
  },
  {
    id: "overview.alerts",
    label: "Overview alerts",
    sectionId: "overview",
    sourcePath: "apps/bayaan-dashboard/src/components/bayaan/overview-dashboard.tsx",
    sourceLines: "285-302",
    visualKind: "status-card",
    bestFor: ["executive-summary", "close-review", "stock-allocation"],
    dataPacks: ["overview", "closing", "inventory"],
    dataContract: "Alert rows with level, title, body, timestamp, and source refs.",
    sourceRefsRequired: ["bayaan.shift.close", "stock.quant", "bayaan.waste.entry"],
    interactionMode: "read-only",
    canvasSizes: ["small", "medium"],
  },
  {
    id: "overview.ai_summary",
    label: "Traceable AI summary",
    sectionId: "overview",
    sourcePath: "apps/bayaan-dashboard/src/components/bayaan/overview-dashboard.tsx",
    sourceLines: "326-335",
    visualKind: "ai-explanation",
    bestFor: ["executive-summary"],
    dataPacks: ["overview", "reports"],
    dataContract: "Short summary with title, body, and source text.",
    sourceRefsRequired: ["report.pack"],
    interactionMode: "read-only",
    canvasSizes: ["medium", "wide"],
  },
  {
    id: "sales.payment_split",
    label: "Payment split",
    sectionId: "sales",
    sourcePath: "apps/bayaan-dashboard/src/components/bayaan/section-dashboard.tsx",
    sourceLines: "393-405",
    visualKind: "progress-list",
    bestFor: ["payment-reconciliation", "executive-summary"],
    dataPacks: ["sales", "finance"],
    dataContract: "Payment method rows with amount and percent value.",
    sourceRefsRequired: ["pos.payment"],
    interactionMode: "read-only",
    canvasSizes: ["small", "medium"],
  },
  {
    id: "sales.gateway_providers",
    label: "Gateway providers",
    sectionId: "sales",
    sourcePath: "apps/bayaan-dashboard/src/components/bayaan/section-dashboard.tsx",
    sourceLines: "407-425",
    visualKind: "table",
    bestFor: ["payment-reconciliation"],
    dataPacks: ["sales", "finance"],
    dataContract: "Provider rows with category, settlement timing, and total.",
    sourceRefsRequired: ["pos.payment", "account.move"],
    interactionMode: "read-only",
    canvasSizes: ["medium", "wide"],
  },
  {
    id: "sales.live_orders_table",
    label: "Live POS orders",
    sectionId: "sales",
    sourcePath: "apps/bayaan-dashboard/src/components/bayaan/section-dashboard.tsx",
    sourceLines: "428-462",
    visualKind: "table",
    bestFor: ["payment-reconciliation", "kiosk-diagnosis", "executive-summary"],
    dataPacks: ["sales", "kiosks"],
    dataContract: "Order rows with time, kiosk, cashier, items, payment, amount, and recipe posting status.",
    sourceRefsRequired: ["pos.order", "pos.payment", "bayaan.consumption.ledger"],
    interactionMode: "read-only",
    canvasSizes: ["wide", "full"],
  },
  {
    id: "sales.live_demo_stream",
    label: "Live demo stream chart",
    sectionId: "sales",
    sourcePath: "apps/bayaan-dashboard/src/components/bayaan/live-demo-panel.tsx",
    sourceLines: "75-110",
    visualKind: "area-chart",
    bestFor: ["executive-summary", "payment-reconciliation"],
    dataPacks: ["sales", "overview"],
    dataContract: "Hourly revenue versus expected series plus order count line.",
    sourceRefsRequired: ["pos.order"],
    interactionMode: "read-only",
    canvasSizes: ["wide", "full"],
  },
  {
    id: "closing.today_closes_table",
    label: "Today's closes",
    sectionId: "closing",
    sourcePath: "apps/bayaan-dashboard/src/components/bayaan/section-dashboard.tsx",
    sourceLines: "706-760",
    visualKind: "table",
    bestFor: ["close-review", "staff-coaching"],
    dataPacks: ["closing", "staff"],
    dataContract: "Close rows with kiosk, cashier, sales, expected/counted cash, variance, status, and investigation state.",
    sourceRefsRequired: ["bayaan.shift.close", "bayaan.shift.close.line", "pos.session"],
    interactionMode: "read-only",
    canvasSizes: ["wide", "full"],
  },
  {
    id: "closing.variance_inputs_expanded",
    label: "Variance inputs",
    sectionId: "closing",
    sourcePath: "apps/kiosk-pos/src/exact-design/ExactKioskApp.jsx",
    sourceLines: "9081-9113",
    visualKind: "expanded-table",
    bestFor: ["close-review", "kiosk-diagnosis", "waste-anomaly-review"],
    dataPacks: ["closing", "inventory", "waste", "sales"],
    dataContract: "Stock lines with opening, received, consumed, waste, expected, counted, and variance.",
    sourceRefsRequired: ["bayaan.shift.close.line", "stock.quant", "bayaan.consumption.ledger", "bayaan.waste.entry"],
    interactionMode: "read-only",
    canvasSizes: ["wide", "full"],
  },
  {
    id: "closing.recipe_posting_review",
    label: "Recipe posting review",
    sectionId: "closing",
    sourcePath: "apps/kiosk-pos/src/exact-design/ExactKioskApp.jsx",
    sourceLines: "9068-9077",
    visualKind: "status-card",
    bestFor: ["close-review", "recipe-margin-review"],
    dataPacks: ["closing", "products", "sales"],
    dataContract: "Paid order posting issues with order references and failure status.",
    sourceRefsRequired: ["pos.order", "bayaan.recipe", "bayaan.consumption.ledger"],
    interactionMode: "read-only",
    canvasSizes: ["medium", "wide"],
  },
  {
    id: "waste.reason_bar_chart",
    label: "Waste reason bar chart",
    sectionId: "waste",
    sourcePath: "apps/kiosk-pos/src/components/studio-dashboard/StudioWasteWorkspace.tsx",
    sourceLines: "42-117",
    visualKind: "bar-chart",
    bestFor: ["waste-anomaly-review", "close-review"],
    dataPacks: ["waste", "closing"],
    dataContract: "Waste reason rows with value and category.",
    sourceRefsRequired: ["bayaan.waste.entry"],
    interactionMode: "read-only",
    canvasSizes: ["medium", "wide"],
  },
  {
    id: "waste.entries_flag_table",
    label: "Flagged waste entries",
    sectionId: "waste",
    sourcePath: "apps/kiosk-pos/src/components/studio-dashboard/StudioWasteWorkspace.tsx",
    sourceLines: "120-180",
    visualKind: "table",
    bestFor: ["waste-anomaly-review", "close-review"],
    dataPacks: ["waste", "closing"],
    dataContract: "Waste rows with time, kiosk, item, quantity, cost, reason, and flagged status.",
    sourceRefsRequired: ["bayaan.waste.entry"],
    interactionMode: "read-only",
    canvasSizes: ["wide", "full"],
  },
  {
    id: "products.recipe_margin_table",
    label: "Recipe cost and margin control",
    sectionId: "products",
    sourcePath: "apps/bayaan-dashboard/src/components/bayaan/section-dashboard.tsx",
    sourceLines: "779-810",
    visualKind: "table",
    bestFor: ["recipe-margin-review", "executive-summary"],
    dataPacks: ["products", "suppliers"],
    dataContract: "Product rows with recipe version, ingredient mode, price, cost, and gross margin.",
    sourceRefsRequired: ["product.template", "bayaan.recipe", "purchase.order"],
    interactionMode: "read-only",
    canvasSizes: ["wide", "full"],
  },
  {
    id: "products.product_list_table",
    label: "Product list",
    sectionId: "products",
    sourcePath: "apps/bayaan-dashboard/src/components/bayaan/section-dashboard.tsx",
    sourceLines: "818-874",
    visualKind: "table",
    bestFor: ["catalog-lookup", "recipe-margin-review"],
    dataPacks: ["products"],
    dataContract: "Product rows with image, category, price, sizes, and recipe status.",
    sourceRefsRequired: ["product.template", "bayaan.recipe"],
    interactionMode: "read-only",
    canvasSizes: ["wide", "full"],
  },
  {
    id: "items.catalog_table",
    label: "Stock item catalog",
    sectionId: "items",
    sourcePath: "apps/kiosk-pos/src/exact-design/ExactKioskApp.jsx",
    sourceLines: "8715-8738",
    visualKind: "table",
    bestFor: ["catalog-lookup", "recipe-margin-review", "stock-allocation"],
    dataPacks: ["items", "inventory", "products"],
    dataContract: "Item rows with category, unit of measure, default supplier, unit cost, and consumption mode.",
    sourceRefsRequired: ["product.template", "stock.quant"],
    interactionMode: "read-only",
    canvasSizes: ["wide", "full"],
  },
  {
    id: "inventory.studio_health_donut",
    label: "Inventory health donut",
    sectionId: "inventory",
    sourcePath: "apps/kiosk-pos/src/components/studio-dashboard/StudioInventoryWorkspace.tsx",
    sourceLines: "291-391",
    visualKind: "donut",
    bestFor: ["stock-allocation", "executive-summary"],
    dataPacks: ["inventory"],
    dataContract: "Healthy, low, and critical stock counts plus stock value and average days cover.",
    sourceRefsRequired: ["stock.quant", "stock.location"],
    interactionMode: "read-only",
    canvasSizes: ["medium", "wide"],
  },
  {
    id: "inventory.studio_ledger_table",
    label: "Inventory ledger",
    sectionId: "inventory",
    sourcePath: "apps/kiosk-pos/src/components/studio-dashboard/StudioInventoryWorkspace.tsx",
    sourceLines: "394-439",
    visualKind: "table",
    bestFor: ["stock-allocation", "catalog-lookup"],
    dataPacks: ["inventory", "items"],
    dataContract: "Inventory rows with item, location, stock, cover, supplier, and status.",
    sourceRefsRequired: ["stock.quant", "stock.location", "product.template"],
    interactionMode: "read-only",
    canvasSizes: ["wide", "full"],
  },
  {
    id: "inventory.studio_transfers_panel",
    label: "Warehouse transfers",
    sectionId: "inventory",
    sourcePath: "apps/kiosk-pos/src/components/studio-dashboard/StudioInventoryWorkspace.tsx",
    sourceLines: "443-492",
    visualKind: "table",
    bestFor: ["stock-allocation", "warehouse-topology"],
    dataPacks: ["inventory", "warehouses"],
    dataContract: "Transfer rows with origin, destination, items, ETA, and state.",
    sourceRefsRequired: ["stock.picking", "stock.location"],
    interactionMode: "proposal-only",
    canvasSizes: ["medium", "wide"],
    notes: "State changes remain human-only. AI can recommend but not advance transfers.",
  },
  {
    id: "inventory.studio_stock_needs_panel",
    label: "Kiosk live stock needs",
    sectionId: "inventory",
    sourcePath: "apps/kiosk-pos/src/components/studio-dashboard/StudioInventoryWorkspace.tsx",
    sourceLines: "494-521",
    visualKind: "proposal-card",
    bestFor: ["stock-allocation", "kiosk-diagnosis"],
    dataPacks: ["inventory", "kiosks"],
    dataContract: "Suggested stock rows with kiosk, item, quantity, cover, reason, and source refs.",
    sourceRefsRequired: ["stock.quant", "stock.location", "bayaan.kiosk"],
    interactionMode: "proposal-only",
    canvasSizes: ["medium", "wide"],
  },
  {
    id: "suppliers.item_catalog_table",
    label: "Supplier item catalog",
    sectionId: "suppliers",
    sourcePath: "apps/bayaan-dashboard/src/components/bayaan/section-dashboard.tsx",
    sourceLines: "924-939",
    visualKind: "table",
    bestFor: ["recipe-margin-review", "stock-allocation"],
    dataPacks: ["suppliers", "products", "inventory"],
    dataContract: "Supplier item rows with unit, supplier, delivery, and margin watch context.",
    sourceRefsRequired: ["purchase.order", "product.template"],
    interactionMode: "read-only",
    canvasSizes: ["medium", "wide"],
  },
  {
    id: "reports.payment_methods_table",
    label: "Payment methods",
    sectionId: "reports",
    sourcePath: "apps/bayaan-dashboard/src/components/bayaan/section-dashboard.tsx",
    sourceLines: "1176-1189",
    visualKind: "table",
    bestFor: ["payment-reconciliation", "executive-summary"],
    dataPacks: ["reports", "finance", "sales"],
    dataContract: "Payment method rows with deterministic amounts.",
    sourceRefsRequired: ["pos.payment", "report.pack"],
    interactionMode: "read-only",
    canvasSizes: ["small", "medium"],
  },
  {
    id: "reports.gateway_settlement_table",
    label: "Iraqi gateway settlement",
    sectionId: "reports",
    sourcePath: "apps/bayaan-dashboard/src/components/bayaan/section-dashboard.tsx",
    sourceLines: "1191-1216",
    visualKind: "table",
    bestFor: ["payment-reconciliation"],
    dataPacks: ["reports", "finance", "sales"],
    dataContract: "Gateway settlement rows with provider, category, settlement timing, and total.",
    sourceRefsRequired: ["pos.payment", "account.move"],
    interactionMode: "read-only",
    canvasSizes: ["medium", "wide"],
  },
  {
    id: "reports.management_report_pack",
    label: "Management report pack",
    sectionId: "reports",
    sourcePath: "apps/bayaan-dashboard/src/components/bayaan/section-dashboard.tsx",
    sourceLines: "1218-1254",
    visualKind: "table",
    bestFor: ["executive-summary", "recipe-margin-review", "stock-allocation", "close-review"],
    dataPacks: ["reports", "finance"],
    dataContract: "Report rows with owner decision, traceable sources, and today signal.",
    sourceRefsRequired: ["report.pack"],
    interactionMode: "read-only",
    canvasSizes: ["wide", "full"],
  },
  {
    id: "reports.pnl_table",
    label: "Profit and loss",
    sectionId: "finance",
    sourcePath: "apps/bayaan-dashboard/src/components/bayaan/section-dashboard.tsx",
    sourceLines: "1256-1274",
    visualKind: "table",
    bestFor: ["executive-summary", "recipe-margin-review"],
    dataPacks: ["finance", "reports"],
    dataContract: "P&L rows with daily, weekly, and monthly deterministic amounts.",
    sourceRefsRequired: ["account.move", "report.pack"],
    interactionMode: "read-only",
    canvasSizes: ["medium", "wide"],
  },
  {
    id: "staff.cashier_performance_table",
    label: "Cashier performance",
    sectionId: "staff",
    sourcePath: "apps/bayaan-dashboard/src/components/bayaan/section-dashboard.tsx",
    sourceLines: "1050-1078",
    visualKind: "table",
    bestFor: ["staff-coaching", "close-review"],
    dataPacks: ["staff", "closing", "sales"],
    dataContract: "Cashier rows with kiosk, sales, cash shortage, voids, and refunds.",
    sourceRefsRequired: ["hr.employee", "pos.order", "bayaan.shift.close"],
    interactionMode: "read-only",
    canvasSizes: ["wide", "full"],
  },
  {
    id: "warehouses.realtime_card",
    label: "Warehouse stock source card",
    sectionId: "warehouses",
    sourcePath: "apps/bayaan-dashboard/src/components/bayaan/section-dashboard.tsx",
    sourceLines: "1595-1657",
    visualKind: "status-card",
    bestFor: ["warehouse-topology", "stock-allocation"],
    dataPacks: ["warehouses", "inventory"],
    dataContract: "Warehouse or kiosk stock node with on-hand, reserved, linked count, availability, and pressure.",
    sourceRefsRequired: ["stock.location", "stock.quant", "bayaan.kiosk"],
    interactionMode: "read-only",
    canvasSizes: ["medium", "wide"],
  },
  {
    id: "warehouses.topology_table",
    label: "Warehouse topology table",
    sectionId: "warehouses",
    sourcePath: "apps/bayaan-dashboard/src/components/bayaan/section-dashboard.tsx",
    sourceLines: "1448-1483",
    visualKind: "table",
    bestFor: ["warehouse-topology", "stock-allocation"],
    dataPacks: ["warehouses", "inventory"],
    dataContract: "Topology rows with type, name, engine record, stock location, quantity, and reserved policy.",
    sourceRefsRequired: ["stock.location", "stock.quant", "bayaan.kiosk"],
    interactionMode: "read-only",
    canvasSizes: ["wide", "full"],
  },
  {
    id: "overview.terminal_status",
    label: "Realtime stream terminal status",
    sectionId: "overview",
    sourcePath: "apps/bayaan-dashboard/src/components/bayaan/overview-dashboard.tsx",
    sourceLines: "362-386",
    visualKind: "status-card",
    bestFor: ["executive-summary"],
    dataPacks: ["overview"],
    dataContract: "Stream health with time, kiosks online, latency, and buffered events.",
    sourceRefsRequired: ["report.pack"],
    interactionMode: "read-only",
    canvasSizes: ["wide", "full"],
  },
  {
    id: "overview.restock_priority_rank",
    label: "Restock priority rank",
    sectionId: "overview",
    sourcePath: "apps/bayaan-dashboard/src/components/bayaan/overview-dashboard.tsx",
    sourceLines: "195-208",
    visualKind: "rank-list",
    bestFor: ["executive-summary", "stock-allocation"],
    dataPacks: ["overview", "inventory", "items"],
    dataContract: "Ranked item rows by urgency with suggested transfer and days-of-cover.",
    sourceRefsRequired: ["stock.quant", "stock.location"],
    interactionMode: "read-only",
    canvasSizes: ["small", "medium"],
  },
  {
    id: "overview.top_products_rank",
    label: "Top products rank",
    sectionId: "overview",
    sourcePath: "apps/bayaan-dashboard/src/components/bayaan/overview-dashboard.tsx",
    sourceLines: "209-220",
    visualKind: "rank-list",
    bestFor: ["executive-summary", "recipe-margin-review"],
    dataPacks: ["overview", "sales", "products"],
    dataContract: "Ranked product rows by revenue with units and percent bars.",
    sourceRefsRequired: ["pos.order", "product.template"],
    interactionMode: "read-only",
    canvasSizes: ["small", "medium"],
  },
  {
    id: "overview.top_waste_rank",
    label: "Top waste rank",
    sectionId: "overview",
    sourcePath: "apps/bayaan-dashboard/src/components/bayaan/overview-dashboard.tsx",
    sourceLines: "221-232",
    visualKind: "rank-list",
    bestFor: ["executive-summary", "waste-anomaly-review"],
    dataPacks: ["overview", "waste"],
    dataContract: "Ranked waste rows by cost with weekly share and status variant.",
    sourceRefsRequired: ["bayaan.waste.entry"],
    interactionMode: "read-only",
    canvasSizes: ["small", "medium"],
  },
  {
    id: "overview.live_activity",
    label: "Live activity stream",
    sectionId: "overview",
    sourcePath: "apps/bayaan-dashboard/src/components/bayaan/overview-dashboard.tsx",
    sourceLines: "254-257",
    visualKind: "timeline",
    bestFor: ["executive-summary", "payment-reconciliation", "close-review"],
    dataPacks: ["overview", "sales"],
    dataContract: "Live event feed rows with time, title, and associated entity refs.",
    sourceRefsRequired: ["pos.order", "pos.payment"],
    interactionMode: "read-only",
    canvasSizes: ["medium", "wide"],
  },
  {
    id: "overview.hourly_pulse",
    label: "Hourly pulse",
    sectionId: "overview",
    sourcePath: "apps/bayaan-dashboard/src/components/bayaan/overview-dashboard.tsx",
    sourceLines: "260-272",
    visualKind: "bar-chart",
    bestFor: ["executive-summary", "kiosk-diagnosis"],
    dataPacks: ["overview", "sales"],
    dataContract: "Hourly revenue bars with expected comparator and max scaling.",
    sourceRefsRequired: ["pos.order", "report.pack"],
    interactionMode: "read-only",
    canvasSizes: ["wide", "full"],
  },
  {
    id: "overview.stock_need_cards",
    label: "Stock need cards",
    sectionId: "overview",
    sourcePath: "apps/bayaan-dashboard/src/components/bayaan/overview-dashboard.tsx",
    sourceLines: "339-356",
    visualKind: "status-card",
    bestFor: ["stock-allocation", "executive-summary"],
    dataPacks: ["overview", "inventory"],
    dataContract: "Per kiosk/item card rows with quantity, cover badge, and transfer suggestion.",
    sourceRefsRequired: ["stock.quant", "stock.location", "bayaan.kiosk"],
    interactionMode: "read-only",
    canvasSizes: ["wide", "full"],
  },
  {
    id: "insights.canvas_grid",
    label: "AI insights canvas grid",
    sectionId: "insights",
    sourcePath: "apps/kiosk-pos/src/exact-design/ExactKioskApp.jsx",
    sourceLines: "5529-5590",
    visualKind: "table",
    bestFor: ["executive-summary", "kiosk-diagnosis", "waste-anomaly-review", "stock-allocation", "close-review"],
    dataPacks: ["overview", "sales", "inventory", "closing", "waste", "products"],
    dataContract: "12-column grid canvas rendering a list of cards with typed renderers.",
    sourceRefsRequired: ["report.pack"],
    interactionMode: "read-only",
    canvasSizes: ["full"],
  },
  {
    id: "insights.chat_panel",
    label: "AI insights chat panel",
    sectionId: "insights",
    sourcePath: "apps/kiosk-pos/src/exact-design/ExactKioskApp.jsx",
    sourceLines: "5916-5923",
    visualKind: "ai-explanation",
    bestFor: ["executive-summary", "kiosk-diagnosis", "waste-anomaly-review"],
    dataPacks: ["overview", "reports"],
    dataContract: "User/AI chat panel that sends a query and drives canvas scene selection.",
    sourceRefsRequired: ["report.pack"],
    interactionMode: "read-only",
    canvasSizes: ["wide", "full"],
  },
  {
    id: "insights.source_meta",
    label: "AI insights source header",
    sectionId: "insights",
    sourcePath: "apps/kiosk-pos/src/exact-design/ExactKioskApp.jsx",
    sourceLines: "5565-5570",
    visualKind: "status-card",
    bestFor: ["executive-summary", "close-review"],
    dataPacks: ["reports", "overview"],
    dataContract: "Header row showing card count and current source citation string.",
    sourceRefsRequired: ["report.pack"],
    interactionMode: "read-only",
    canvasSizes: ["wide", "full"],
  },
  {
    id: "insights.studio_cards",
    label: "Studio AI insight cards",
    sectionId: "insights",
    sourcePath: "apps/bayaan-dashboard/src/components/bayaan/section-dashboard.tsx",
    sourceLines: "134-148",
    visualKind: "status-card",
    bestFor: ["executive-summary", "waste-anomaly-review", "kiosk-diagnosis"],
    dataPacks: ["overview", "reports"],
    dataContract: "Insight cards with kind, title, body, and confidence progress bars.",
    sourceRefsRequired: ["report.pack"],
    interactionMode: "read-only",
    canvasSizes: ["wide", "full"],
  },
  {
    id: "insights.studio_traceable_cards",
    label: "Studio traceable insight cards",
    sectionId: "insights",
    sourcePath: "apps/bayaan-dashboard/src/components/bayaan/section-dashboard.tsx",
    sourceLines: "150-158",
    visualKind: "ai-explanation",
    bestFor: ["executive-summary", "close-review", "payment-reconciliation"],
    dataPacks: ["reports", "finance"],
    dataContract: "Compact traceable insight cards with explicit source text lines.",
    sourceRefsRequired: ["report.pack"],
    interactionMode: "read-only",
    canvasSizes: ["wide", "full"],
  },
  {
    id: "insights.suggested_questions",
    label: "Suggested owner questions",
    sectionId: "insights",
    sourcePath: "apps/bayaan-dashboard/src/components/bayaan/section-dashboard.tsx",
    sourceLines: "184-191",
    visualKind: "progress-list",
    bestFor: ["executive-summary"],
    dataPacks: ["overview"],
    dataContract: "List of suggested prompts for common owner questions.",
    sourceRefsRequired: ["report.pack"],
    interactionMode: "read-only",
    canvasSizes: ["small", "medium"],
  },
  {
    id: "kiosks.kpi_grid",
    label: "Kiosk fleet KPI grid",
    sectionId: "kiosks",
    sourcePath: "apps/bayaan-dashboard/src/components/bayaan/section-dashboard.tsx",
    sourceLines: "249-274",
    visualKind: "kpi-grid",
    bestFor: ["executive-summary", "kiosk-diagnosis"],
    dataPacks: ["kiosks"],
    dataContract: "Counts and averages for kiosk status, revenue, inventory, and waste.",
    sourceRefsRequired: ["pos.order", "stock.quant", "bayaan.waste.entry", "bayaan.kiosk"],
    interactionMode: "read-only",
    canvasSizes: ["wide", "full"],
  },
  {
    id: "kiosks.city_filter",
    label: "Kiosk city filter",
    sectionId: "kiosks",
    sourcePath: "apps/bayaan-dashboard/src/components/bayaan/section-dashboard.tsx",
    sourceLines: "276-288",
    visualKind: "status-card",
    bestFor: ["kiosk-diagnosis"],
    dataPacks: ["kiosks"],
    dataContract: "City filter button group for narrowing kiosk comparisons.",
    sourceRefsRequired: ["bayaan.kiosk"],
    interactionMode: "read-only",
    canvasSizes: ["small", "medium"],
  },
  {
    id: "kiosks.sort_segmented",
    label: "Kiosk sort segmented control",
    sectionId: "kiosks",
    sourcePath: "apps/bayaan-dashboard/src/components/bayaan/section-dashboard.tsx",
    sourceLines: "293-302",
    visualKind: "status-card",
    bestFor: ["kiosk-diagnosis"],
    dataPacks: ["kiosks"],
    dataContract: "Sort segmented control for status, revenue, inventory, or waste ordering.",
    sourceRefsRequired: ["bayaan.kiosk"],
    interactionMode: "read-only",
    canvasSizes: ["small", "medium"],
  },
  {
    id: "kiosks.view_toggle",
    label: "Kiosk view toggle",
    sectionId: "kiosks",
    sourcePath: "apps/bayaan-dashboard/src/components/bayaan/section-dashboard.tsx",
    sourceLines: "303-310",
    visualKind: "status-card",
    bestFor: ["kiosk-diagnosis"],
    dataPacks: ["kiosks"],
    dataContract: "Cards vs table toggle for kiosk list presentation.",
    sourceRefsRequired: ["bayaan.kiosk"],
    interactionMode: "read-only",
    canvasSizes: ["small", "medium"],
  },
  {
    id: "kiosks.realtime_card",
    label: "Realtime kiosk card",
    sectionId: "kiosks",
    sourcePath: "apps/bayaan-dashboard/src/components/bayaan/section-dashboard.tsx",
    sourceLines: "1527-1600",
    visualKind: "status-card",
    bestFor: ["kiosk-diagnosis"],
    dataPacks: ["kiosks", "sales", "inventory", "waste"],
    dataContract: "Per-kiosk status card with live pulse, revenue, orders, margin, and inventory/waste meters.",
    sourceRefsRequired: ["pos.order", "stock.quant", "bayaan.waste.entry", "bayaan.kiosk"],
    interactionMode: "read-only",
    canvasSizes: ["medium", "wide"],
  },
  {
    id: "kiosks.table",
    label: "Kiosk fleet table",
    sectionId: "kiosks",
    sourcePath: "apps/bayaan-dashboard/src/components/bayaan/section-dashboard.tsx",
    sourceLines: "326-348",
    visualKind: "table",
    bestFor: ["kiosk-diagnosis", "executive-summary"],
    dataPacks: ["kiosks", "sales", "inventory", "waste"],
    dataContract: "Dense table with status, revenue, orders, inventory, waste, and margin.",
    sourceRefsRequired: ["pos.order", "stock.quant", "bayaan.waste.entry", "bayaan.kiosk"],
    interactionMode: "read-only",
    canvasSizes: ["wide", "full"],
  },
  {
    id: "warehouses.kpi_grid",
    label: "Warehouse topology KPI grid",
    sectionId: "warehouses",
    sourcePath: "apps/bayaan-dashboard/src/components/bayaan/section-dashboard.tsx",
    sourceLines: "1367-1374",
    visualKind: "kpi-grid",
    bestFor: ["warehouse-topology", "stock-allocation"],
    dataPacks: ["warehouses", "inventory"],
    dataContract: "Counts for warehouses, kiosk locations, POS configs, and source readiness.",
    sourceRefsRequired: ["stock.location", "stock.quant"],
    interactionMode: "read-only",
    canvasSizes: ["wide", "full"],
  },
  {
    id: "warehouses.engine_status",
    label: "Warehouse engine configuration status",
    sectionId: "warehouses",
    sourcePath: "apps/bayaan-dashboard/src/components/bayaan/section-dashboard.tsx",
    sourceLines: "1376-1388",
    visualKind: "status-card",
    bestFor: ["warehouse-topology"],
    dataPacks: ["warehouses"],
    dataContract: "Engine configured/not-configured block with refresh hint.",
    sourceRefsRequired: ["report.pack"],
    interactionMode: "read-only",
    canvasSizes: ["wide", "full"],
  },
  {
    id: "warehouses.topology_toolbar",
    label: "Warehouse topology toolbar",
    sectionId: "warehouses",
    sourcePath: "apps/bayaan-dashboard/src/components/bayaan/section-dashboard.tsx",
    sourceLines: "1399-1416",
    visualKind: "status-card",
    bestFor: ["warehouse-topology", "stock-allocation"],
    dataPacks: ["warehouses"],
    dataContract: "Scope, sort, and view controls for warehouse topology browsing.",
    sourceRefsRequired: ["stock.location"],
    interactionMode: "read-only",
    canvasSizes: ["wide", "full"],
  },
  {
    id: "items.category_filter",
    label: "Item category filter",
    sectionId: "items",
    sourcePath: "apps/kiosk-pos/src/exact-design/ExactKioskApp.jsx",
    sourceLines: "8707-8713",
    visualKind: "status-card",
    bestFor: ["catalog-lookup"],
    dataPacks: ["items"],
    dataContract: "Category selector and related filter control for stock items.",
    sourceRefsRequired: ["product.template"],
    interactionMode: "read-only",
    canvasSizes: ["small", "medium"],
  },
  {
    id: "items.new_item_modal",
    label: "New stock item modal",
    sectionId: "items",
    sourcePath: "apps/kiosk-pos/src/exact-design/ExactKioskApp.jsx",
    sourceLines: "8741-8771",
    visualKind: "expanded-table",
    bestFor: ["catalog-lookup"],
    dataPacks: ["items"],
    dataContract: "Human-only stock item creation form; never AI-executable in v1.",
    sourceRefsRequired: ["product.template"],
    interactionMode: "human-action",
    canvasSizes: ["wide", "full"],
    notes: "AI must not call create item flows; render only as a human action surface.",
  },
  {
    id: "sales.kpi_grid",
    label: "Sales KPI grid",
    sectionId: "sales",
    sourcePath: "apps/bayaan-dashboard/src/components/bayaan/section-dashboard.tsx",
    sourceLines: "382-389",
    visualKind: "kpi-grid",
    bestFor: ["executive-summary", "payment-reconciliation"],
    dataPacks: ["sales", "finance"],
    dataContract: "POS orders, cash expected, digital payments, and issue count needing review.",
    sourceRefsRequired: ["pos.order", "pos.payment"],
    interactionMode: "read-only",
    canvasSizes: ["wide", "full"],
  },
  {
    id: "closing.kpi_grid",
    label: "Closing KPI grid",
    sectionId: "closing",
    sourcePath: "apps/bayaan-dashboard/src/components/bayaan/section-dashboard.tsx",
    sourceLines: "690-698",
    visualKind: "kpi-grid",
    bestFor: ["close-review", "executive-summary"],
    dataPacks: ["closing"],
    dataContract: "Pending reviews, approved closes, and cash/stock variance totals.",
    sourceRefsRequired: ["bayaan.shift.close", "bayaan.shift.close.line"],
    interactionMode: "read-only",
    canvasSizes: ["wide", "full"],
  },
  {
    id: "closing.variance_loop_explanation",
    label: "Variance loop explanation",
    sectionId: "closing",
    sourcePath: "apps/bayaan-dashboard/src/components/bayaan/section-dashboard.tsx",
    sourceLines: "700-704",
    visualKind: "ai-explanation",
    bestFor: ["close-review", "executive-summary"],
    dataPacks: ["closing", "inventory", "waste"],
    dataContract: "Deterministic expected-vs-counted explanation block for operator training.",
    sourceRefsRequired: ["bayaan.shift.close", "bayaan.consumption.ledger", "bayaan.waste.entry"],
    interactionMode: "read-only",
    canvasSizes: ["wide", "full"],
  },
  {
    id: "closing.active_review_table",
    label: "Active close review table",
    sectionId: "closing",
    sourcePath: "apps/kiosk-pos/src/exact-design/ExactKioskApp.jsx",
    sourceLines: "8925-8955",
    visualKind: "expanded-table",
    bestFor: ["close-review"],
    dataPacks: ["closing", "staff", "sales"],
    dataContract: "Human-only close table with approve/reject/note controls and expanded variance drilldown.",
    sourceRefsRequired: ["bayaan.shift.close", "bayaan.shift.close.line", "pos.session"],
    interactionMode: "human-action",
    canvasSizes: ["full"],
    notes: "AI must not approve or review closes in v1; render only as a manager-operated surface.",
  },
  {
    id: "waste.kpi_grid",
    label: "Waste KPI grid",
    sectionId: "waste",
    sourcePath: "apps/bayaan-dashboard/src/components/bayaan/section-dashboard.tsx",
    sourceLines: "614-622",
    visualKind: "kpi-grid",
    bestFor: ["waste-anomaly-review", "executive-summary"],
    dataPacks: ["waste", "sales"],
    dataContract: "Waste loss today, 7-day loss, percent of revenue, and anomaly count.",
    sourceRefsRequired: ["bayaan.waste.entry", "pos.order"],
    interactionMode: "read-only",
    canvasSizes: ["wide", "full"],
  },
  {
    id: "waste.reason_control",
    label: "Waste reason control",
    sectionId: "waste",
    sourcePath: "apps/bayaan-dashboard/src/components/bayaan/section-dashboard.tsx",
    sourceLines: "624-634",
    visualKind: "bar-chart",
    bestFor: ["waste-anomaly-review", "close-review"],
    dataPacks: ["waste"],
    dataContract: "Reason-by-category grid with value totals per reason.",
    sourceRefsRequired: ["bayaan.waste.entry"],
    interactionMode: "read-only",
    canvasSizes: ["wide", "full"],
  },
  {
    id: "waste.pattern_ai_block",
    label: "Waste pattern AI block",
    sectionId: "waste",
    sourcePath: "apps/bayaan-dashboard/src/components/bayaan/section-dashboard.tsx",
    sourceLines: "636-640",
    visualKind: "ai-explanation",
    bestFor: ["waste-anomaly-review"],
    dataPacks: ["waste", "sales"],
    dataContract: "Compact finding explaining a detected waste pattern with actionable narrative.",
    sourceRefsRequired: ["bayaan.waste.entry", "pos.order"],
    interactionMode: "read-only",
    canvasSizes: ["wide", "full"],
  },
  {
    id: "waste.entries_table",
    label: "Waste entries table",
    sectionId: "waste",
    sourcePath: "apps/bayaan-dashboard/src/components/bayaan/section-dashboard.tsx",
    sourceLines: "642-666",
    visualKind: "table",
    bestFor: ["waste-anomaly-review", "close-review"],
    dataPacks: ["waste"],
    dataContract: "Waste entries with time, kiosk, item, qty, cost, reason, and flagged indicator.",
    sourceRefsRequired: ["bayaan.waste.entry"],
    interactionMode: "read-only",
    canvasSizes: ["wide", "full"],
  },
  {
    id: "products.kpi_grid",
    label: "Products KPI grid",
    sectionId: "products",
    sourcePath: "apps/bayaan-dashboard/src/components/bayaan/section-dashboard.tsx",
    sourceLines: "768-777",
    visualKind: "kpi-grid",
    bestFor: ["recipe-margin-review", "executive-summary"],
    dataPacks: ["products"],
    dataContract: "Product count, recipe coverage, custom images, and missing recipe count.",
    sourceRefsRequired: ["product.template", "bayaan.recipe"],
    interactionMode: "read-only",
    canvasSizes: ["wide", "full"],
  },
  {
    id: "products.persistence_ai_block",
    label: "Product persistence explanation",
    sectionId: "products",
    sourcePath: "apps/bayaan-dashboard/src/components/bayaan/section-dashboard.tsx",
    sourceLines: "812-816",
    visualKind: "ai-explanation",
    bestFor: ["recipe-margin-review", "executive-summary"],
    dataPacks: ["products"],
    dataContract: "Explains demo/local persistence vs engine-backed persistence.",
    sourceRefsRequired: ["report.pack"],
    interactionMode: "read-only",
    canvasSizes: ["wide", "full"],
  },
  {
    id: "products.active_editor",
    label: "Active product editor",
    sectionId: "products",
    sourcePath: "apps/kiosk-pos/src/exact-design/ExactKioskApp.jsx",
    sourceLines: "9689-9716",
    visualKind: "expanded-table",
    bestFor: ["recipe-margin-review"],
    dataPacks: ["products", "items"],
    dataContract: "Human-only editor that can upsert product catalog and submit recipe versions to the engine.",
    sourceRefsRequired: ["product.template", "bayaan.recipe"],
    interactionMode: "human-action",
    canvasSizes: ["full"],
    notes: "AI must never call upsert/submit methods in v1; show as human action only.",
  },
  {
    id: "suppliers.open_po_table",
    label: "Open purchase orders",
    sectionId: "suppliers",
    sourcePath: "apps/bayaan-dashboard/src/components/bayaan/section-dashboard.tsx",
    sourceLines: "890-918",
    visualKind: "table",
    bestFor: ["recipe-margin-review", "stock-allocation"],
    dataPacks: ["suppliers", "inventory", "items"],
    dataContract: "Open purchase orders with supplier, invoice, warehouse, items, value, and status.",
    sourceRefsRequired: ["purchase.order", "product.template"],
    interactionMode: "read-only",
    canvasSizes: ["wide", "full"],
  },
  {
    id: "suppliers.recurring_purchases_table",
    label: "Recurring purchases table",
    sectionId: "suppliers",
    sourcePath: "apps/bayaan-dashboard/src/components/bayaan/section-dashboard.tsx",
    sourceLines: "942-970",
    visualKind: "table",
    bestFor: ["stock-allocation", "executive-summary"],
    dataPacks: ["suppliers", "inventory"],
    dataContract: "Recurring purchase plans with schedule, items, and suggested action.",
    sourceRefsRequired: ["purchase.order"],
    interactionMode: "proposal-only",
    canvasSizes: ["wide", "full"],
    notes: "AI must render plan actions as proposals only in v1.",
  },
  {
    id: "suppliers.supplier_table",
    label: "Supplier table",
    sectionId: "suppliers",
    sourcePath: "apps/bayaan-dashboard/src/components/bayaan/section-dashboard.tsx",
    sourceLines: "985-1012",
    visualKind: "table",
    bestFor: ["recipe-margin-review", "executive-summary"],
    dataPacks: ["suppliers"],
    dataContract: "Supplier list with category, delivery time, spend, and last order.",
    sourceRefsRequired: ["purchase.order"],
    interactionMode: "read-only",
    canvasSizes: ["wide", "full"],
  },
  {
    id: "inventory.warehouse_allocation_table",
    label: "Warehouse and kiosk allocation table",
    sectionId: "inventory",
    sourcePath: "apps/bayaan-dashboard/src/components/bayaan/section-dashboard.tsx",
    sourceLines: "468-530",
    visualKind: "table",
    bestFor: ["stock-allocation"],
    dataPacks: ["inventory", "items", "warehouses"],
    dataContract: "Item/location allocation rows with stock, reorder threshold, days of cover, and allocate button.",
    sourceRefsRequired: ["stock.quant", "stock.location", "product.template"],
    interactionMode: "proposal-only",
    canvasSizes: ["wide", "full"],
    notes: "Allocate actions must be proposal-only for AI in v1.",
  },
  {
    id: "inventory.transfer_execution_card",
    label: "Transfer execution card",
    sectionId: "inventory",
    sourcePath: "apps/bayaan-dashboard/src/components/bayaan/section-dashboard.tsx",
    sourceLines: "1489-1522",
    visualKind: "status-card",
    bestFor: ["stock-allocation", "warehouse-topology"],
    dataPacks: ["inventory", "warehouses"],
    dataContract: "Transfer rows with from/to, item, qty, ETA, and state badge.",
    sourceRefsRequired: ["stock.picking"],
    interactionMode: "proposal-only",
    canvasSizes: ["medium", "wide"],
    notes: "New transfer entry is a human action; AI renders as proposal-only.",
  },
  {
    id: "inventory.kiosk_live_needs_table",
    label: "Kiosk live stock needs table",
    sectionId: "inventory",
    sourcePath: "apps/bayaan-dashboard/src/components/bayaan/section-dashboard.tsx",
    sourceLines: "520-548",
    visualKind: "table",
    bestFor: ["stock-allocation", "kiosk-diagnosis"],
    dataPacks: ["inventory", "items", "kiosks"],
    dataContract: "Per kiosk/item needs rows with qty, cover, reason, and create transfer control.",
    sourceRefsRequired: ["stock.quant", "stock.location", "bayaan.kiosk"],
    interactionMode: "proposal-only",
    canvasSizes: ["wide", "full"],
    notes: "Create transfer button must never execute in v1; show as recommendation only.",
  },
  {
    id: "staff.kpi_grid",
    label: "Staff KPI grid",
    sectionId: "staff",
    sourcePath: "apps/bayaan-dashboard/src/components/bayaan/section-dashboard.tsx",
    sourceLines: "1036-1048",
    visualKind: "kpi-grid",
    bestFor: ["staff-coaching", "executive-summary"],
    dataPacks: ["staff"],
    dataContract: "Staff totals for active staff, payroll, hours, and under-review count.",
    sourceRefsRequired: ["hr.employee", "hr.attendance"],
    interactionMode: "read-only",
    canvasSizes: ["wide", "full"],
  },
  {
    id: "staff.expenses_table",
    label: "Staff expenses table",
    sectionId: "staff",
    sourcePath: "apps/bayaan-dashboard/src/components/bayaan/section-dashboard.tsx",
    sourceLines: "1080-1099",
    visualKind: "table",
    bestFor: ["executive-summary"],
    dataPacks: ["staff", "finance"],
    dataContract: "Operating expense rows with category and deterministic amount.",
    sourceRefsRequired: ["account.move", "report.pack"],
    interactionMode: "proposal-only",
    canvasSizes: ["wide", "full"],
    notes: "Adding expenses is a human action; AI renders as read-only/proposal-only.",
  },
  {
    id: "staff.roster_table",
    label: "Staff roster table",
    sectionId: "staff",
    sourcePath: "apps/bayaan-dashboard/src/components/bayaan/section-dashboard.tsx",
    sourceLines: "1105-1124",
    visualKind: "table",
    bestFor: ["staff-coaching"],
    dataPacks: ["staff"],
    dataContract: "Roster rows with staff member, role, kiosk, hours, salary, and status.",
    sourceRefsRequired: ["hr.employee", "hr.attendance"],
    interactionMode: "read-only",
    canvasSizes: ["wide", "full"],
  },
  {
    id: "reports.ai_summary",
    label: "Reports AI summary",
    sectionId: "reports",
    sourcePath: "apps/bayaan-dashboard/src/components/bayaan/section-dashboard.tsx",
    sourceLines: "1162-1166",
    visualKind: "ai-explanation",
    bestFor: ["executive-summary", "recipe-margin-review", "payment-reconciliation"],
    dataPacks: ["reports", "finance"],
    dataContract: "Daily report narrative summary with revenue and net profit headline.",
    sourceRefsRequired: ["report.pack"],
    interactionMode: "read-only",
    canvasSizes: ["wide", "full"],
  },
  {
    id: "reports.kpi_grid",
    label: "Reports KPI grid",
    sectionId: "reports",
    sourcePath: "apps/bayaan-dashboard/src/components/bayaan/section-dashboard.tsx",
    sourceLines: "1168-1174",
    visualKind: "kpi-grid",
    bestFor: ["executive-summary", "recipe-margin-review"],
    dataPacks: ["reports", "finance"],
    dataContract: "Revenue, COGS, and net profit KPI rows.",
    sourceRefsRequired: ["account.move", "report.pack"],
    interactionMode: "read-only",
    canvasSizes: ["wide", "full"],
  },
] as const satisfies readonly DashboardComponentEntry[];

export type DashboardComponentId = (typeof componentRegistry)[number]["id"];

export function getDashboardComponent(id: DashboardComponentId): DashboardComponentEntry {
  const component = componentRegistry.find((entry) => entry.id === id);
  if (!component) {
    throw new Error(`Unknown dashboard component: ${id}`);
  }
  return component;
}

export function getComponentsForIntent(intent: AiDashboardIntent): DashboardComponentEntry[] {
  return componentRegistry.filter((entry) => (entry.bestFor as readonly AiDashboardIntent[]).includes(intent));
}

export function isAiRenderable(entry: DashboardComponentEntry): boolean {
  return (
    entry.interactionMode === "read-only" ||
    entry.interactionMode === "proposal-only" ||
    entry.interactionMode === "human-confirm"
  );
}

export function assertAiRenderable(componentIds: readonly DashboardComponentId[]) {
  const blocked = componentIds
    .map((id) => getDashboardComponent(id))
    .filter((entry) => !isAiRenderable(entry));

  if (blocked.length) {
    throw new Error(`AI plan includes human-action components: ${blocked.map((entry) => entry.id).join(", ")}`);
  }
}
