from . import bayaan_kiosk
from . import product_template
from . import res_partner
from . import pos_payment_method
from . import bayaan_recipe
from . import bayaan_consumption
from . import bayaan_shift_close
from . import bayaan_waste
from . import bayaan_audit_event
from . import bayaan_realtime
from . import pos_order
from . import stock_picking
from . import bayaan_payment_transaction
from . import bayaan_recurring_purchase
from . import bayaan_hr_payroll
from . import ir_websocket
from . import demo_seed
